# 사용자 정의 속성
profile:
  value: 'test'

spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
    redis:
      host: localhost
      port: 6379
  datasource:
    url: ${TEST_DB_URL}

    username: ${TEST_DB_USERNAME}
    password: ${TEST_DB_PASSWORD}


  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        format_sql: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
kakao:
  secret:
    key: ${KAKAO_PAY_SECRET_KEY}
cid: ${KAKAO_PAY_CID}

hostUrl: http://localhost:8080

